### ISSUE TITLE
Uninstalling Apache

### ISSUE THREAD

**Issue by timbroder** [geerlingguy/ansible-role-apache#102]
I'm moving from Apache to nginx (using your package for that). 

Can you recommend how I should uninstall apache using this package? (or point me in the right direction)

Thank you

**Comment by geerlingguy** [comment]
@timbroder - I don't generally add any 'uninstall' or 'remove' steps to my roles, because I generally will rebuild a server or image from scratch if I need to change the way it's built. If you want to uninstall everything, it depends slightly on your OS package manager and what packages you have installed, but for Ubuntu, you'd do an `apt-get remove --purge [packages]` to remove the package and configuration.

**Comment by timbroder** [comment]
@geerlingguy thanks much
