### ISSUE TITLE
a2dissite and a2ensite support

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-apache#104]
Now I have to do this:

```
- name: be sure default virtualhost file is disabled
  command: a2dissite 000-default
  notify: restart apache

- name: be sure graphite virtualhost is enabled
  command: a2ensite apache2-graphite
  notify: restart apache
```

Would it be possible to add `a2dissite and a2ensite support`, also check whether these commands have been executed and define in a hash or something:

```
a2ensite:
   - apache2-graphite
a2dissite:
   - 000-default
```

**Comment by geerlingguy** [comment]
@030 - Since I mostly use non-Ubuntu/Debian servers, I don't like to rely on specific wrapper utilities that are OS-specific like `a2ensite` when possible.

Also, you can have the default virtualhost disabled using `apache_remove_default_vhost: true` (see the README: https://github.com/geerlingguy/ansible-role-apache#role-variables). And you can control the vhost name so it's set as `apache2-graphite` using `apache_vhosts_filename` (also in README file).
