### ISSUE TITLE
use native a2enmod instead of symlink

### ISSUE THREAD

**Issue by splashx** [geerlingguy/ansible-role-apache#106]
Any reason why use [symlinks](https://github.com/geerlingguy/ansible-role-apache/blob/master/tasks/configure-Debian.yml#L11) and not to the [native ansible apache2](http://docs.ansible.com/ansible/apache2_module_module.html) module?

**Comment by geerlingguy** [comment]
@splashx - Because I generally use CentOS instead of Ubuntu, so I'd rather do symlinks for easier maintenance and a more obvious layout of where files are, how they're referenced, etc.

I'm not a fan of Deb/Ubuntu's affinity for adding extra utilities to try to mask weird configuration file layouts that are geared towards hand-managed servers. The point of automation is to do away with the strangeness that is 'sites-enabled' and 'sites-available' and things like that—if you use Ansible, there's no reason to be storing configurations that are 'available' but not 'enabled'... just store the active configurations on prod, and don't store unused configs.

**Comment by splashx** [comment]
Hi there. Thanks for the explanation. 
However I had linked the Debian yml file - nowhere I mentioned centos/RH. 
Since there is already a separate Debian yml and being the above-mentioned module a core ansible module, blabling about your personal opionion about a distro you don't use is pointless...

**Comment by geerlingguy** [comment]
@splashx - I _do_ use it, I probably have somewhere around 50 servers running Debian, Raspbian, or Ubuntu. I just don't prefer it, and use CentOS on most of my other servers. Someday, I could change the role to do something different and maybe use the built-in module, it's just not a priority, as the way it is now works fine and makes more sense to me.
