### ISSUE TITLE
How can I upgrade Apache using your role

### ISSUE THREAD

**Issue by heatherita** [geerlingguy/ansible-role-apache#122]
Hi!

I've been testing your role and it seems to work fine. I'm using an ec2 instance which is Red Hat 4.8.3-9. Your role gives me apache 2.2 Can I run your role to upgrade tp apache 2.4 while remaining on Red Hat 4.8? I've been trying to do this by editing the configuration. Here are some of the things I've tried:

In vars/RedHat.yml change "httpd" to:
```
__apache_packages:
  - httpd24-httpd 
  - httpd24-httpd-devel
  - mod_ssl
  - openssh
```
also:
`apache_vhosts_version: "2.4"`
(instead of "2.2")

Another idea was in defaults/main.yml:

`apache_packages_state: latest`
(instead of apache_packages_state: installed)

or should I change ` apache_enablerepo: ""` to something else? But I don't know what the possible values for this variable are. 

Please advise if possible. thanks.

**Comment by geerlingguy** [comment]
@heatherita - I'm not sure it's possible to run Apache 2.4 on Red Hat 4.x—I know I've seen some people struggle tremendously to get it on Red Hat 5... and it's not the most fun to have it work well on Red Hat 6.

Also, this role only minimally supports Red Hat 6, but fully supports 7. Red Hat 4 itself is just about of it's extended-extended-extended life support (https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates), and I'd recommend spending time working on upgrading to a newer version of Red Hat rather than trying to get a modern version of Apache running on it :/

**Comment by geerlingguy** [comment]
But in general, the way to upgrade versions (e.g. if you were on Red Hat 6), is to install a `yum` repository that has a newer version of Apache, then set `apache_packages_state` to `latest` (as you mentioned. At that point, the role would upgrade to whatever version is available in that repo.

**Comment by heatherita** [comment]
@geerlingguy . I see what you mean about the newer Apache not being compatible with the RHEL. In that case I'll try to get an AWS image with RHEL 7 instead, that will be easy enough.

And thanks for the general advice on how to upgrade apache with your role, in case I ever need to. Have a great weekend!

Heather

**Comment by geerlingguy** [comment]
@heatherita - No problem!
