### ISSUE TITLE
Simplifying docker exec commands

### ISSUE THREAD

**Issue by jamesmontalvo3** [geerlingguy/ansible-role-apache#124]
If you have lots of `docker exec` commands in your `.travis.yml` file, it can make it a lot easier to read by capturing the common arguments into an array variable. This is particularly necessary if any of the lines are long. So if you have a lot of these:

```yaml
- 'docker exec --tty "$(cat ${container_id})" env TERM=xterm some command with lots "of args"'
```

You can turn them into this:

```yaml
# Wrap all the `docker exec ...` in an array for clarity
- 'docker_exec=( docker exec --tty "$(cat ${container_id})" env TERM=xterm )'

- '${docker_exec[@]} some command with lots "of args"'
```

I've used your blog and repos to learn Ansible and testing on Docker and Travis. Thanks for everything! I modified one of your `.travis.yml` files for one of my projects and started doing the `docker_exec` thing above, and just figured I'd pass it along.

**Comment by geerlingguy** [comment]
@jamesmontalvo3 - Since I use the same basic layout for all 70+ roles I have on GitHub, I can't make the change in one place without making it everywhere (just for simplicity in cross-role maintenance).

I have been thinking about a few improvements to my current test format, but there's a good reason I keep things broken out a bit—some roles run into issues sometimes when `TERM=xterm` is set, others hit a snag with the `--tty` option... this is currently as bare/efficient as I want to get for maintenance reasons (and reproducibility in other environments).

I've even considered switching to something like molecule at some point, but I'm kinda 'NIH' in my role maintenance mentality... whether that's a good thing or bad, I've been able to continuously maintain these roles without a bad effect on my family life for the past 3 years, so there's that :D
