### ISSUE TITLE
Doesn't work on Linux Mint

### ISSUE THREAD

**Issue by miloskroulik** [geerlingguy/ansible-role-apache#32]
On linux mint, I get following result:
````
$ ansible localhost -m setup | grep ansible_os_family
        "ansible_os_family": "Linuxmint",
````
That's a problem, because file includes don't work.

It works fine, if I add following at the top of `main.yml` file:

````
# Ensure correct fact
- set_fact: ansible_os_family="Debian"
  when: ansible_os_family == "Debian" or ansible_os_family == "Linuxmint"
````

**Comment by geerlingguy** [comment]
Since I don't run Mint, nor plan to set up a CI environment for it (I only regularly use CentOS, Ubuntu, or Debian), I'd rather not add 'official' support for Mint (since I don't like supporting OSes that I don't actually test when developing the role.

However, your workaround *should* continue to work, at least for most aspects of this role, and I'd recommend if you wish to continue using this role with Mint, you can just continue adding that configuration to your playbooks. (And maybe reset the ansible_os_family back to `Linuxmint` after the role is complete).
