### ISSUE TITLE
Allow global ServerName setting

### ISSUE THREAD

**Issue by fritz-c** [geerlingguy/ansible-role-apache#37]
When deploying apache 2.4 on Ubuntu Trusty, I get the following warning:
`msg: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.2.15. Set the 'ServerName' directive globally to suppress this message`
Perhaps an optional setting such as the one below could be inserted [here](https://github.com/geerlingguy/ansible-role-apache/blob/master/templates/vhosts-2.4.conf.j2#L3).

```
{% if apache_global_server_name is defined %}
  ServerName {{ apache_global_server_name }}
{% endif %}
```

**Comment by geerlingguy** [comment]
I definitely woundn't be opposed to this addition—however, do you know if this feature will break (cause to not start) Apache < 2.4?

**Comment by drivard** [comment]
I don't believe it would break Apache <2.4 since both of the following documentation includes the ServerName dirrective.

https://httpd.apache.org/docs/2.0/mod/core.html#servername
https://httpd.apache.org/docs/2.2/mod/core.html#servername

I would probably change the snippet by something like 

in `defaults/main.yml`

		apache_global_server_name: "localhost"

I guess in `vhosts.conf.j2`

		ServerName {{ apache_global_server_name }}

By letting the default ServerName to localhost apache starts correctly and it removes the warning from the logs.

I thought there would be a problem with having ServerName directive with the same name declared multiple times in the vhosts configuration files, but I tested it on an Ubuntu 16.04 and apache started without any issue and the status shows good state. I had 3 vhosts on the server while testing and they all contained `ServerName localhost`.

		systemctl status apache2.service
		apache2.service - LSB: Apache2 web server
		   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
		  Drop-In: /lib/systemd/system/apache2.service.d
		           └─apache2-systemd.conf
		   Active: active (running) since Wed 2017-08-30 10:03:39 EDT; 10s ago
		     Docs: man:systemd-sysv-generator(8)
		  Process: 37213 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
		  Process: 36797 ExecReload=/etc/init.d/apache2 reload (code=exited, status=0/SUCCESS)
		  Process: 37237 ExecStart=/etc/init.d/apache2 start (code=exited, status=0/SUCCESS)
		    Tasks: 55
		   Memory: 6.7M
		      CPU: 65ms
		   CGroup: /system.slice/apache2.service
		           ├─37254 /usr/sbin/apache2 -k start
		           ├─37257 /usr/sbin/apache2 -k start
		           └─37258 /usr/sbin/apache2 -k start

		Aug 30 10:03:38 webserver systemd[1]: Stopped LSB: Apache2 web server.
		Aug 30 10:03:38 webserver systemd[1]: Starting LSB: Apache2 web server...
		Aug 30 10:03:38 webserver apache2[37237]:  * Starting Apache httpd web server apache2
		Aug 30 10:03:39 webserver apache2[37237]:  *
		Aug 30 10:03:39 webserver systemd[1]: Started LSB: Apache2 web server.

the vhosts	
		
		/etc/apache2/sites-enabled# ll
		total 8
		drwxr-xr-x 2 root root 4096 Aug 30 10:03 ./
		drwxr-xr-x 8 root root 4096 Aug 30 10:01 ../
		lrwxrwxrwx 1 root root   35 Aug 30 09:35 000-default.conf -> ../sites-available/000-default.conf
		lrwxrwxrwx 1 root root   32 Aug 30 09:41 webserver.conf -> ../sites-available/webserver.conf
		lrwxrwxrwx 1 root root   40 Aug 30 09:35 vhosts.conf -> /etc/apache2/sites-available/vhosts.conf
		
Hope it can help.

**Comment by drivard** [comment]
Just figured out to bypass the current issue until the feature is added you can add to your variables file the following snippet and it will terminate the warning.

		apache_global_vhost_settings: |
			ServerName "www.example.com"
