### ISSUE TITLE
Compatibility with ansible 2.0 devel

### ISSUE THREAD

**Issue by rsanzante** [geerlingguy/ansible-role-apache#48]
Using last commit form ansible 2.0 I get this error:

>TASK [geerlingguy.apache : Get installed version of Apache.] *******************
fatal: [ansiblito]: FAILED! => {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1446343835.9-147459737534108/command\", line 2386, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1446343835.9-147459737534108/command\", line 158, in main\r\n    module = CommandModule(argument_spec=dict())\r\n  File \"/root/.ansible/tmp/ansible-tmp-1446343835.9-147459737534108/command\", line 761, in __init__\r\n    self._check_arguments(check_invalid_arguments)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1446343835.9-147459737534108/command\", line 1304, in _check_arguments\r\n    for (k,v) in self.params.items():\r\nAttributeError: 'tuple' object has no attribute 'items'\r\n", "parsed": false}

**Comment by geerlingguy** [comment]
This sounds like a potential regression in Ansible core; a week ago, there was no issue with any of my Apache server configs with Ansible 2.0.0 devel, so if this is breaking now but wasn't then, it's something that would need to be fixed there.

Also, the error message itself is a little funny; the 'Get installed version' task doesn't even use `items`, so it sounds like an internal error message.

**Comment by geerlingguy** [comment]
Also note that I won't be officially supporting Ansible 2.0.0 until the final stable version is released. I've been tracking devel for the past few months and so far have made sure things work every few weeks, but there's a new core bug here and there (which you may be running into this time) so I recommend people stick to the last stable release (currently 1.9.4) because that's the only _actually_ supported version, and the only version I run all my tests against.

**Comment by rsanzante** [comment]
Yes, probably is that, I shouldn't post this issue until a stable release, sorry for the noise.
