### ISSUE TITLE
Change name of vars for vhost configuration so they match those from ansible-role-nginx

### ISSUE THREAD

**Issue by frob** [geerlingguy/ansible-role-apache#52]
It would be nice to be able to use the same vhost configuration for both apache and nginx incase there is a need to switch. Or in the case of Drupal-vm where two global vhost lists need to be maintained, one for apache and one for nginx.

**Comment by geerlingguy** [comment]
One problem with this approach is that there are valid use cases where Apache and Nginx reside on the same server, but are used for different purposes. Also, it's best practice to prefix every role variable with the role name to avoid namespace collisions.

Long term, for Drupal VM specificially, I hope to address the issue by using a single `drupal_sites` list with all the requisite information... but for now I'm choosing to leave it as-is just because I don't want the additional complexity since Apache vhosts are much different than Nginx server directives.
