### ISSUE TITLE
Implement the sites-enabled/-available on CentOS too

### ISSUE THREAD

**Issue by patkar** [geerlingguy/ansible-role-apache#93]
It would be a nice idea to implement the `sites-available` / `sites-enabled` vhost structure on CentOS too.

**Comment by geerlingguy** [comment]
As someone who comes from the RHEL/CentOS background and only started supporting Debian-style distros after Debian 6 and Ubuntu 12... I don't particularly like using individual vhosts per file, but I'm not 100% opposed to it either.

The whole sites-enabled vs. sites-available thing doesn't jive with my idea of immutable infrastructure or infrastructure-as-code, because it implies that you'll have some switches/manual processes that could turn on or off a vhost outside of a normal server configuration run.

**Comment by geerlingguy** [comment]
I'm going to move the discussion over to #94 because I'm definitely not going to switch OS package defaults to implement a symlink-based approach where there is none (I don't want to surprise people used to the RHEL style by tossing in weird Debian conventions all the sudden :) ).
