### ISSUE TITLE
Configure its vhost in it's own file

### ISSUE THREAD

**Issue by patkar** [geerlingguy/ansible-role-apache#94]
Configure each vhost (or the pair of non ssl and ssl) in its own file. So you can disable/enable each vhost separately. At least for debian based systems or even cent os if #93 is implemented ;)

**Comment by geerlingguy** [comment]
As someone who comes from the RHEL/CentOS background and only started supporting Debian-style distros after Debian 6 and Ubuntu 12... I don't particularly like using individual vhosts per file, but I'm not 100% opposed to it either.

The whole sites-enabled vs. sites-available thing doesn't jive with my idea of immutable infrastructure or infrastructure-as-code, because it implies that you'll have some switches/manual processes that could turn on or off a vhost outside of a normal server configuration run.

**Comment by afelle1** [comment]
I agree with @patkar that there should be an option of managing vhosts in separate conf.d files.  I don't think the background really matters here (I'm a RHEL/CentOS guy too) as vhost specific files allow administrators of multi-tenant hosts to give tenants access to their relevant files thus enforcing security practices of restricted access and it's arguable that separate files are more readable / maintainable.  I also prefer minimizing automation touching systems, so this would allow minimal changes possible.  The apache conf.d style of configuration has been around for quite a while, so it is as established method of configuration as conf/httpd.conf.  Lastly, I know [Puppet supports this](https://forge.puppet.com/puppetlabs/apache), so obviously people in general want it.

$0.02

**Comment by furester** [comment]
ATM i'm adding multiple time the role, one for each vhost/vhost-file i want to be created, side effect for this solution is that the role is invoked multiple time.

**Comment by patkar** [comment]
After working more and more with it, I finally disagree with my first statement here. If you have separate files per vhost you end up with vhost files not removed if you simply remove the vhost configuration from the roles variables. You would need to specify the vhost explicitly as `state: absent` (which must be supported by the role) to have it removed, run the playbook and then you can finally remove the vhost completely from the roles variables.

And as a second argument on a managed and immutable infrastructure it shouldn't matter how much vhosts are in one config file. IMHO you should never be the one to touch or read them ;)
Separate files are only useful in manually managed servers.

**Comment by geerlingguy** [comment]
> And as a second argument on a managed and immutable infrastructure it shouldn't matter how much vhosts are in one config file. IMHO you should never be the one to touch or read them ;)

Agreed, and it definitely removes a lot of complexity (e.g. the whole 'enabled' vs. 'available' configuration thing)!

**Comment by furester** [comment]
my 2¢..
I use single vhost conf file to manage properly certbot\letsencrypt certificare renew, i need this because renewal require that in the .conf file there is only a single ssl vhost (using Debian Jessie, certbot from testing). ATM i repeat the role multiple time, but it requires lot of repetitions.

**Comment by ArondeParon** [comment]
👍 

Regardless of personal preference, I think this would be a really nice option to have. A lot of people, myself included, prefer to keep vhost configuration separated by file. As @furester mentioned, Certbot also requires each host to be contained in it's own configuration file as mentioned in in https://github.com/certbot/certbot/issues/1042.

Perhaps a flag like `apache_separate_vhosts` would be useful?
